/// Represents the HTMLConvertible ``<abbr>`` tag.
public let Abbreviation = GenericElement(tag: "abbr")
/// Represents the HTMLConvertible ``<address>`` tag.
public let Address = GenericElement(tag: "address")
/// Represents the HTMLConvertible ``<article>`` tag.
public let Article = GenericElement(tag: "article")
/// Represents the HTMLConvertible ``<aside>`` tag.
public let Aside = GenericElement(tag: "aside")
/// Represents the HTMLConvertible ``<bdi>`` tag.
public let BidirectionalIsolate = GenericElement(tag: "bdi")
/// Represents the HTMLConvertible ``<bdo>`` tag.
public let BidirectionalTextOverride  = GenericElement(tag: "bdo")
/// Represents the HTMLConvertible ``<blockquote>`` tag.
public let BlockQuotation = GenericElement(tag: "blockquote")
/// Represents the HTMLConvertible ``<body>`` tag.
public let Body = GenericElement(tag: "body")
/// Represents the HTMLConvertible ``<caption>`` tag.
public let Caption = GenericElement(tag: "caption")
/// Represents the HTMLConvertible ``<cite>`` tag.
public let Citation = GenericElement(tag: "cite")
/// Represents the HTMLConvertible ``<dfn>`` tag.
public let Definition = GenericElement(tag: "dfn")
/// Represents the HTMLConvertible ``<dd>`` tag.
public let DescriptionDetails = GenericElement(tag: "dd")
/// Represents the HTMLConvertible ``<dt>`` tag.
public let DescriptionTerm = GenericElement(tag: "dt")
/// Represents the HTMLConvertible ``<fieldset>`` tag.
public let FieldSet = GenericElement(tag: "fieldset")
/// Represents the HTMLConvertible ``<figure>`` tag.
public let Figure = GenericElement(tag: "figure")
/// Represents the HTMLConvertible ``<figcaption>`` tag.
public let FigureCaption = GenericElement(tag: "figcaption")
/// Represents the HTMLConvertible ``<footer>`` tag.
public let Footer = GenericElement(tag: "footer")
/// Represents the HTMLConvertible ``<div>`` tag.
public let Group = GenericElement(tag: "div")
/// Represents the HTMLConvertible ``<head>`` tag.
public let Head = GenericElement(tag: "head")
/// Represents the HTMLConvertible ``<header>`` tag.
public let Header = GenericElement(tag: "header")
/// Represents the HTMLConvertible ``<code>`` tag.
public let InlineCode = GenericElement(tag: "code")
/// Represents the HTMLConvertible ``<kbd>`` tag.
public let KeyboardIput = GenericElement(tag: "kbd")
/// Represents the HTMLConvertible ``<legend>`` tag.
public let Legend = GenericElement(tag: "legend")
/// Represents the HTMLConvertible ``<li>`` tag.
public let ListItem = GenericElement(tag: "li")
/// Represents the HTMLConvertible ``<main>`` tag.
public let Main = GenericElement(tag: "main")
/// Represents the HTMLConvertible ``<nav>`` tag.
public let Navigation = GenericElement(tag: "nav")
/// Represents the HTMLConvertible ``<noscript>`` tag.
public let NoScript = GenericElement(tag: "noscript")
/// Represents the HTMLConvertible ``<object>`` tag.
public let Object = GenericElement(tag: "object")
/// Represents the HTMLConvertible ``<p>`` tag.
public let Paragraph = GenericElement(tag: "p")
/// Represents the HTMLConvertible ``<picture>`` tag.
public let Picture = GenericElement(tag: "picture")
/// Represents the HTMLConvertible ``<pre>`` tag.
public let PreformattedText = GenericElement(tag: "pre")
/// Represents the HTMLConvertible ``<q>`` tag.
public let Quotation = GenericElement(tag: "q")
/// Represents the HTMLConvertible ``<ruby>`` tag.
public let Ruby = GenericElement(tag: "ruby")
/// Represents the HTMLConvertible ``<rp>`` tag.
public let RubyParenthesis = GenericElement(tag: "rp")
/// Represents the HTMLConvertible ``<rt>`` tag.
public let RubyText = GenericElement(tag: "rt")
/// Represents the HTMLConvertible ``<samp>`` tag.
public let SampleOutput = GenericElement(tag: "samp")
/// Represents the HTMLConvertible ``<section>`` tag.
public let Section = GenericElement(tag: "section")
/// Represents the HTMLConvertible ``<span>`` tag.
public let Span = GenericElement(tag: "span")
/// Represents the HTMLConvertible ``<summary>`` tag.
public let Summary = GenericElement(tag: "summary")
/// Represents the HTMLConvertible ``<table>`` tag.
public let Table = GenericElement(tag: "table")
/// Represents the HTMLConvertible ``<tbody>`` tag.
public let TableBody = GenericElement(tag: "tbody")
/// Represents the HTMLConvertible ``<th>`` tag.
public let TableCellHeader = GenericElement(tag: "th")
/// Represents the HTMLConvertible ``<td>`` tag.
public let TableData = GenericElement(tag: "td")
/// Represents the HTMLConvertible ``<tfoot>`` tag.
public let TableFooter = GenericElement(tag: "tfoot")
/// Represents the HTMLConvertible ``<thead>`` tag.
public let TableHeader = GenericElement(tag: "thead")
/// Represents the HTMLConvertible ``<tr>`` tag.
public let TableRow = GenericElement(tag: "tr")
/// Represents the HTMLConvertible ``<template>`` tag.
public let Template = GenericElement(tag: "template")
/// Represents the HTMLConvertible ``<title>`` tag.
public let Title = GenericElement(tag: "title")
/// Represents the HTMLConvertible ``<var>`` tag.
public let Variable = GenericElement(tag: "var")
