/// Represents the HTML ``<abbr>`` tag.
public let Abbreviation = GenericElement(tag: "abbr")
/// Represents the HTML ``<address>`` tag.
public let Address = GenericElement(tag: "address")
/// Represents the HTML ``<a>`` tag.
public let Anchor = GenericElement(tag: "a")
/// Represents the HTML ``<article>`` tag.
public let Article = GenericElement(tag: "article")
/// Represents the HTML ``<aside>`` tag.
public let Aside = GenericElement(tag: "aside")
/// Represents the HTML ``<audio>`` tag.
public let Audio = GenericElement(tag: "audio")
/// Represents the HTML ``<bdi>`` tag.
public let BidirectionalIsolate = GenericElement(tag: "bdi")
/// Represents the HTML ``<bdo>`` tag.
public let BidirectionalTextOverride  = GenericElement(tag: "bdo")
/// Represents the HTML ``<blockquote>`` tag.
public let BlockQuotation = GenericElement(tag: "blockquote")
/// Represents the HTML ``<body>`` tag.
public let Body = GenericElement(tag: "body")
/// Represents the HTML ``<button>`` tag.
public let Button = GenericElement(tag: "button")
/// Represents the HTML ``<canvas>`` tag.
public let Canvas = GenericElement(tag: "canvas")
/// Represents the HTML ``<caption>`` tag.
public let Caption = GenericElement(tag: "caption")
/// Represents the HTML ``<cite>`` tag.
public let Citation = GenericElement(tag: "cite")
/// Represents the HTML ``<colgroup>`` tag.
public let ColumnGroup = GenericElement(tag: "colgroup")
/// Represents the HTML ``<data>`` tag.
public let Data = GenericElement(tag: "data")
/// Represents the HTML ``<dfn>`` tag.
public let Definition = GenericElement(tag: "dfn")
/// Represents the HTML ``<dd>`` tag.
public let DescriptionDetails = GenericElement(tag: "dd")
/// Represents the HTML ``<dt>`` tag.
public let DescriptionTerm = GenericElement(tag: "dt")
/// Represents the HTML ``<details>`` tag.
public let Details = GenericElement(tag: "details")
/// Represents the HTML ``<dialog>`` tag.
public let Dialog = GenericElement(tag: "dialog")
/// Represents the HTML ``<div>`` tag.
public let Division = GenericElement(tag: "div")
/// Represents the HTML ``<fieldset>`` tag.
public let FieldSet = GenericElement(tag: "fieldset")
/// Represents the HTML ``<figure>`` tag.
public let Figure = GenericElement(tag: "figure")
/// Represents the HTML ``<figcaption>`` tag.
public let FigureCaption = GenericElement(tag: "figcaption")
/// Represents the HTML ``<footer>`` tag.
public let Footer = GenericElement(tag: "footer")
/// Represents the HTML ``<form>`` tag.
public let Form = GenericElement(tag: "form")
/// Represents the HTML ``<html>`` tag.
public let Root = GenericElement(tag: "html")
/// Represents the HTML ``<head>`` tag.
public let Head = GenericElement(tag: "head")
/// Represents the HTML ``<header>`` tag.
public let Header = GenericElement(tag: "header")
/// Represents the HTML ``<h1>`` tag.
public let Heading1 = GenericElement(tag: "h1")
/// Represents the HTML ``<h2>`` tag.
public let Heading2 = GenericElement(tag: "h2")
/// Represents the HTML ``<h3>`` tag.
public let Heading3 = GenericElement(tag: "h3")
/// Represents the HTML ``<h4>`` tag.
public let Heading4 = GenericElement(tag: "h4")
/// Represents the HTML ``<h5>`` tag.
public let Heading5 = GenericElement(tag: "h5")
/// Represents the HTML ``<h6>`` tag.
public let Heading6 = GenericElement(tag: "h6")
/// Represents the HTML ``<iframe>`` tag.
public let iFrame = GenericElement(tag: "iframe")
/// Represents the HTML ``<code>`` tag.
public let InlineCode = GenericElement(tag: "code")
/// Represents the HTML ``<kbd>`` tag.
public let KeyboardIput = GenericElement(tag: "kbd")
/// Represents the HTML ``<legend>`` tag.
public let Legend = GenericElement(tag: "legend")
/// Represents the HTML ``<li>`` tag.
public let ListItem = GenericElement(tag: "li")
/// Represents the HTML ``<main>`` tag.
public let Main = GenericElement(tag: "main")
/// Represents the HTML ``<meter>`` tag.
public let Meter = GenericElement(tag: "meter")
/// Represents the HTML ``<nav>`` tag.
public let Navigation = GenericElement(tag: "nav")
/// Represents the HTML ``<noscript>`` tag.
public let NoScript = GenericElement(tag: "noscript")
/// Represents the HTML ``<object>`` tag.
public let Object = GenericElement(tag: "object")
/// Represents the HTML ``<option>`` tag.
public let Option = GenericElement(tag: "option")
/// Represents the HTML ``<optgroup>`` tag.
public let OptionGroup = GenericElement(tag: "optgroup")
/// Represents the HTML ``<output>`` tag.
public let Output = GenericElement(tag: "output")
/// Represents the HTML ``<p>`` tag.
public let Paragraph = GenericElement(tag: "p")
/// Represents the HTML ``<picture>`` tag.
public let Picture = GenericElement(tag: "picture")
/// Represents the HTML ``<pre>`` tag.
public let PreformattedText = GenericElement(tag: "pre")
/// Represents the HTML ``<q>`` tag.
public let Quotation = GenericElement(tag: "q")
/// Represents the HTML ``<ruby>`` tag.
public let Ruby = GenericElement(tag: "ruby")
/// Represents the HTML ``<rp>`` tag.
public let RubyParenthesis = GenericElement(tag: "rp")
/// Represents the HTML ``<rt>`` tag.
public let RubyText = GenericElement(tag: "rt")
/// Represents the HTML ``<samp>`` tag.
public let SampleOutput = GenericElement(tag: "samp")
/// Represents the HTML ``<section>`` tag.
public let Section = GenericElement(tag: "section")
/// Represents the HTML ``<select>`` tag.
public let Select = GenericElement(tag: "select")
/// Represents the HTML ``<span>`` tag.
public let Span = GenericElement(tag: "span")
/// Represents the HTML ``<summary>`` tag.
public let Summary = GenericElement(tag: "summary")
/// Represents the HTML ``<table>`` tag.
public let Table = GenericElement(tag: "table")
/// Represents the HTML ``<tbody>`` tag.
public let TableBody = GenericElement(tag: "tbody")
/// Represents the HTML ``<th>`` tag.
public let TableCellHeader = GenericElement(tag: "th")
/// Represents the HTML ``<td>`` tag.
public let TableData = GenericElement(tag: "td")
/// Represents the HTML ``<tfoot>`` tag.
public let TableFooter = GenericElement(tag: "tfoot")
/// Represents the HTML ``<thead>`` tag.
public let TableHeader = GenericElement(tag: "thead")
/// Represents the HTML ``<tr>`` tag.
public let TableRow = GenericElement(tag: "tr")
/// Represents the HTML ``<template>`` tag.
public let Template = GenericElement(tag: "template")
/// Represents the HTML ``<textarea>`` tag.
public let TextArea = GenericElement(tag: "textarea")
/// Represents the HTML ``<title>`` tag.
public let Title = GenericElement(tag: "title")
/// Represents the HTML ``<var>`` tag.
public let Variable = GenericElement(tag: "var")
/// Represents the HTML ``<video>`` tag.
public let Video = GenericElement(tag: "video")
