public enum Attribute: String {
    case accept
    case acceptcharset = "accept-charset"
    case accesskey
    case action
    case align
    case alt
    case autocomplete
    case bgcolor
    case border
    case charset
    case cite
    case `class`
    case color
    case cols
    case colspan
    case contenteditable
    case coords
    case crossorigin
    case data
    case datetime
    case `defer`
    case dir
    case dirname
    case download
    case draggable
    case enctype
    case `for`
    case form
    case formaction
    case headers
    case height
    case high
    case href
    case hreflang
    case httpequiv = "http-equiv"
    case id
    case integrity
    case kind
    case label
    case lang
    case list
    case low
    case max
    case maxlength
    case media
    case method
    case min
    case name
    case onabort
    case onafterprint
    case onbeforeprint
    case onbeforeunload
    case onblur
    case oncanplay
    case oncanplaythrough
    case onchange
    case onclick
    case oncontextmenu
    case oncopy
    case oncuechange
    case oncut
    case ondblclick
    case ondrag
    case ondragend
    case ondragenter
    case ondragleave
    case ondragover
    case ondragstart
    case ondrop
    case ondurationchange
    case onemptied
    case onended
    case onerror
    case onfocus
    case onhashchange
    case oninput
    case oninvalid
    case onkeydown
    case onkeypress
    case onkeyup
    case onload
    case onloadeddata
    case onloadedmetadata
    case onloadstart
    case onmousedown
    case onmousemove
    case onmouseout
    case onmouseover
    case onmouseup
    case onmousewheel
    case onoffline
    case ononline
    case onpagehide
    case onpageshow
    case onpaste
    case onpause
    case onplay
    case onplaying
    case onpopstate
    case onprogress
    case onratechange
    case onreset
    case onresize
    case onscroll
    case onsearch
    case onseeked
    case onseeking
    case onselect
    case onstalled
    case onstorage
    case onsubmit
    case onsuspend
    case ontimeupdate
    case ontoggle
    case onunload
    case onvolumechange
    case onwaiting
    case onwheel
    case optimum
    case pattern
    case placeholder
    case poster
    case preload
    case referrerpolicy
    case rel
    case rows
    case rowspan
    case sandbox
    case scope
    case shape
    case size
    case sizes
    case span
    case spellcheck
    case src
    case srcdoc
    case srclang
    case srcset
    case start
    case step
    case style
    case tabindex
    case target
    case title
    case translate
    case type
    case usemap
    case value
    case width
    case wrap
    case empty
}

public enum BooleanAttribute: String {
    case allowfullscreen
    case allowpaymentrequest
    case `async`
    case autofocus
    case autoplay
    case checked
    case controls
    case `default`
    case disabled
    case formnovalidate
    case hidden
    case ismap
    case itemscope
    case loop
    case multiple
    case muted
    case nomudule
    case novalidate
    case open
    case playsinline
    case readonly
    case required
    case reversed
    case selected
    case truespeed
}
