public enum EventAttribute: String {
    case abort
    case afterprint
    case beforeprint
    case beforeunload
    case blur
    case canplay
    case canplaythrough
    case change
    case click
    case ctextmenu
    case copy
    case cuechange
    case cut
    case dblclick
    case drag
    case dragend
    case dragenter
    case dragleave
    case dragover
    case dragstart
    case drop
    case durationchange
    case emptied
    case ended
    case error
    case focus
    case hashchange
    case input
    case invalid
    case keydown
    case keypress
    case keyup
    case load
    case loadeddata
    case loadedmetadata
    case loadstart
    case mousedown
    case mousemove
    case mouseout
    case mouseover
    case mouseup
    case mousewheel
    case offline
    case line
    case pagehide
    case pageshow
    case paste
    case pause
    case play
    case playing
    case popstate
    case progress
    case ratechange
    case reset
    case resize
    case scroll
    case search
    case seeked
    case seeking
    case select
    case stalled
    case storage
    case submit
    case suspend
    case timeupdate
    case toggle
    case unload
    case volumechange
    case waiting
    case wheel
}
